import Link from "next/link";
import { ArrowRight, Building2, Factory, Home } from "lucide-react";
import Container from "@/components/Container";
import PageHero from "@/components/PageHero";
import SectionHeading from "@/components/SectionHeading";
import { buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({ title: "Glasgow Asbestos Project Library", description: "Explore representative asbestos project workflows for Glasgow homes, shared buildings and industrial premises.", path: "/project-library" });

const scenarios = [
  { icon: Home, area: "Glasgow homeowner journey", title: "Suspected cement garage roof", problem: "A homeowner is planning replacement work on a weathered outbuilding roof.", approach: "Confirm existing evidence, assess condition and access, determine work category, then provide a defined removal and disposal scope.", pack: "Written scope, relevant work records and applicable waste documentation." },
  { icon: Building2, area: "Tenement and factor journey", title: "Refurbishment in shared premises", problem: "Planned work may disturb older finishes or panels in a flat or common area.", approach: "Clarify who controls the area and what work is planned, then identify the appropriate survey before contractors begin.", pack: "Survey information, location records, action recommendations and information for affected contractors." },
  { icon: Factory, area: "Commercial and industrial journey", title: "Roofing or cladding programme", problem: "A live site needs planned work without losing control of access, operations or documentation.", approach: "Review the survey and task, define work zones and programme constraints, and coordinate the applicable non-licensed or NNLW scope.", pack: "Agreed scope, work controls, completion evidence and waste records." },
];

export default function ProjectLibraryPage() {
  return <><PageHero eyebrow="Representative workflows" title="Glasgow Project Library" intro="See how common enquiries move from uncertainty to a controlled next step. These are representative workflows—not claims about unnamed completed customers." crumbs={[{ label: "Home", href: "/" }, { label: "Project Library", href: "/project-library" }]} /><section className="py-16 sm:py-20"><Container><SectionHeading eyebrow="How we approach the work" title="Problem, decision, documentation" intro="Verified customer case studies and photographs will be added only with permission and supporting project records." /><div className="mt-10 grid gap-6 lg:grid-cols-3">{scenarios.map(({ icon: Icon, area, title, problem, approach, pack }) => <article key={title} className="overflow-hidden rounded-2xl border border-line bg-white shadow-card"><div className="gradient-hero p-6 text-white"><Icon className="h-7 w-7 text-eco-400" aria-hidden="true" /><p className="mt-4 font-mono text-xs uppercase tracking-wider text-white/65">{area}</p><h2 className="mt-2 font-display text-xl font-bold">{title}</h2></div><dl className="space-y-5 p-6 text-sm"><div><dt className="font-semibold text-brand-950">The situation</dt><dd className="mt-1 leading-relaxed text-slate-600">{problem}</dd></div><div><dt className="font-semibold text-brand-950">The decision path</dt><dd className="mt-1 leading-relaxed text-slate-600">{approach}</dd></div><div><dt className="font-semibold text-brand-950">Typical project pack</dt><dd className="mt-1 leading-relaxed text-slate-600">{pack}</dd></div></dl></article>)}</div><div className="mt-10 text-center"><Link href="/clarity-check" className="inline-flex min-h-12 items-center rounded-full bg-brand-950 px-6 py-3 text-sm font-semibold text-white">Start with your property <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" /></Link></div></Container></section></>;
}
